title: >
  <center><a href="#"><img src="img/Peatland-Technologies-logo.jpg" width="750"></a></center>
  <h4><strong>Contact:</strong> <a href="mfloyd@peatland-technologies.com"><font color="white">mfloyd@peatland-technologies.com</font></a></h4>
description: energy to fight climate change
theme: jekyll-theme-cayman
github:
  is_project_page: false
