title: >
  <center><img src="" width="500" height="200"></center>
  <a href="#" style="color: white; text-decoration: none">Peatland Technologies, LLC</a>
  <h4><strong>Contact:</strong> <a href="mfloyd@peatland-technologies.com"><font color="white">mfloyd@peatland-technologies.com</font></a></h4>
description: energy to fight climate change
theme: jekyll-theme-cayman
github:
  is_project_page: false
